//! The `code` module contains types and helper methods to format and manage the
//! code generated by this crate.

mod format;
mod ident_path;
mod module;

pub use self::format::{
    format_field_ident, format_module_ident, format_type_ident, format_variant_ident,
};
pub use self::ident_path::{IdentPath, ModulePath};
pub use self::module::Module;
