pub type BmecatElement = BmecatElementType;
#[derive(Debug)]
pub struct BmecatElementType {
    pub version: TypeBmEcatVersion,
    pub content: Vec<BmecatElementTypeContent>,
}
#[derive(Debug)]
pub enum BmecatElementTypeContent {
    Header(HeaderElementType),
    TNewCatalog(TNewCatalogElementType),
    TUpdateProducts(TUpdateProductsElementType),
    TUpdatePrices(TUpdatePricesElementType),
}
#[derive(Debug)]
pub enum TypeBmEcatVersion {
    _12,
    _2005,
}
#[derive(Debug)]
pub struct HeaderElementType {
    pub generator_info: Option<String>,
    pub catalog: CatalogElementType,
    pub buyer: BuyerElementType,
    pub supplier: SupplierElementType,
    pub user_defined_extensions: UdxHeader,
}
#[derive(Debug)]
pub struct TNewCatalogElementType {
    pub product: Vec<TNewCatalogProductElementType>,
}
#[derive(Debug)]
pub struct TUpdateProductsElementType {
    pub prev_version: i32,
    pub product: Vec<TUpdateProductsProductElementType>,
}
#[derive(Debug)]
pub struct TUpdatePricesElementType {
    pub prev_version: i32,
    pub product: Vec<TUpdatePricesProductElementType>,
}
#[derive(Debug)]
pub struct CatalogElementType {
    pub language: Vec<LanguageElementType>,
    pub catalog_id: String,
    pub catalog_version: String,
    pub catalog_name: Vec<DtMlstring>,
    pub datetime: CatalogDatetimeElementType,
    pub territory: Vec<String>,
    pub currency: Option<DtCurrencies>,
    pub mime_root: Vec<DtMlstring>,
}
#[derive(Debug)]
pub struct BuyerElementType {
    pub buyer_id: Option<TypePartyId>,
    pub buyer_name: String,
}
#[derive(Debug)]
pub struct SupplierElementType {
    pub supplier_id: Vec<TypePartyId>,
    pub supplier_name: String,
    pub address: Option<SupplierAddressElementType>,
    pub mime_info: Option<MimeInfoElementType>,
}
#[derive(Debug)]
pub struct UdxHeader {
    pub udx_edxf_version: String,
}
#[derive(Debug)]
pub struct TNewCatalogProductElementType {
    pub mode: TNewCatalogMode,
    pub supplier_pid: SupplierPidElementType,
    pub product_details: ProductDetailsElementType,
    pub product_features: Vec<ProductFeaturesElementType>,
    pub product_order_details: ProductOrderDetailsElementType,
    pub product_price_details: Vec<ProductPriceDetailsElementType>,
    pub mime_info: Option<MimeInfoElementType>,
    pub user_defined_extensions: UdxProduct,
    pub product_reference: Vec<ProductReferenceElementType>,
    pub product_logistic_details: Option<ProductLogisticDetailsElementType>,
}
#[derive(Debug)]
pub struct TUpdateProductsProductElementType {
    pub mode: TUpdateProductsMode,
    pub supplier_pid: SupplierPidElementType,
    pub product_details: ProductDetailsElementType,
    pub product_features: Vec<ProductFeaturesElementType>,
    pub product_order_details: ProductOrderDetailsElementType,
    pub product_price_details: Vec<ProductPriceDetailsElementType>,
    pub mime_info: Option<MimeInfoElementType>,
    pub user_defined_extensions: Option<UdxProduct>,
    pub product_reference: Vec<ProductReferenceElementType>,
    pub product_logistic_details: Option<ProductLogisticDetailsElementType>,
}
#[derive(Debug)]
pub struct TUpdatePricesProductElementType {
    pub mode: TUpdatePricesMode,
    pub supplier_pid: SupplierPidElementType,
    pub product_price_details: Vec<ProductPriceDetailsElementType>,
    pub user_defined_extensions: Option<UdxProduct>,
}
#[derive(Debug)]
pub struct LanguageElementType {
    pub default: Option<String>,
    pub content: DtLang,
}
#[derive(Debug)]
pub struct DtMlstring {
    pub lang: Option<DtLang>,
    pub content: String,
}
#[derive(Debug)]
pub struct CatalogDatetimeElementType {
    pub type_: CatalogType,
    pub date: String,
    pub time: Option<String>,
    pub timezone: Option<String>,
}
#[derive(Debug)]
pub enum DtCurrencies {
    Adp,
    Aed,
    Afa,
    All,
    Ang,
    Aok,
    Ara,
    Ats,
    Aud,
    Awg,
    Bbd,
    Bdt,
    Bef,
    Bgl,
    Bhd,
    Bif,
    Bmd,
    Bnd,
    Bob,
    Brc,
    Bsd,
    Btn,
    Buk,
    Bwp,
    Bzd,
    Cad,
    Chf,
    Clf,
    Clp,
    Cny,
    Cop,
    Crc,
    Csk,
    Cup,
    Cve,
    Cyp,
    Ddm,
    Dem,
    Djf,
    Dkk,
    Dop,
    Dzd,
    Ecs,
    Egp,
    Esp,
    Etb,
    Eur,
    Fim,
    Fjd,
    Fkp,
    Frf,
    Gbp,
    Ghc,
    Gip,
    Gmd,
    Gnf,
    Grd,
    Gtq,
    Gwp,
    Gyd,
    Hkd,
    Hnl,
    Htg,
    Huf,
    Idr,
    Iep,
    Ils,
    Inr,
    Iqd,
    Irr,
    Isk,
    Itl,
    Jmd,
    Jod,
    Jpy,
    Kes,
    Khr,
    Kmf,
    Kpw,
    Krw,
    Kwd,
    Kyd,
    Lak,
    Lbp,
    Lkr,
    Lrd,
    Lsl,
    Luf,
    Lyd,
    Mad,
    Mgf,
    Mnt,
    Mop,
    Mro,
    Mtl,
    Mur,
    Mvr,
    Mwk,
    Mxp,
    Myr,
    Mzm,
    Ngn,
    Nic,
    Nlg,
    Nok,
    Npr,
    Nzd,
    Omr,
    Pab,
    Pei,
    Pgk,
    Php,
    Pkr,
    Plz,
    Pln,
    Pte,
    Pyg,
    Qar,
    Rol,
    Rwf,
    Sar,
    Sbd,
    Scr,
    Sdp,
    Sek,
    Sgd,
    Shp,
    Sll,
    Skk,
    Sos,
    Srg,
    Std,
    Sur,
    Svc,
    Syp,
    Szl,
    Thb,
    Tnd,
    Top,
    Tpe,
    Trl,
    Ttd,
    Twd,
    Tzs,
    Ugs,
    Usd,
    Uyp,
    Veb,
    Vnd,
    Vuv,
    Wst,
    Ydd,
    Yer,
    Yud,
    Zar,
    Zmk,
    Zrz,
    Zwd,
}
#[derive(Debug)]
pub struct TypePartyId {
    pub type_: Option<String>,
    pub content: String,
}
#[derive(Debug)]
pub struct SupplierAddressElementType {
    pub type_: SupplierType,
    pub contact: Vec<DtMlstring>,
    pub street: Vec<DtMlstring>,
    pub zip: Vec<DtMlstring>,
    pub city: Vec<DtMlstring>,
    pub country: Vec<DtMlstring>,
    pub vat_id: Option<String>,
    pub email: String,
    pub url: Option<String>,
}
#[derive(Debug)]
pub struct MimeInfoElementType {
    pub mime: Vec<MimeElementType>,
}
#[derive(Debug)]
pub enum TNewCatalogMode {
    New,
}
#[derive(Debug)]
pub struct SupplierPidElementType {
    pub type_: Option<String>,
    pub content: String,
}
#[derive(Debug)]
pub struct ProductDetailsElementType {
    pub description_short: Vec<DtMlstring>,
    pub description_long: Vec<DtMlstring>,
    pub international_pid: Vec<InternationalPidElementType>,
    pub supplier_alt_pid: Option<String>,
    pub buyer_pid: Vec<BuyerPidElementType>,
    pub manufacturer_pid: Option<String>,
    pub manufacturer_name: Option<String>,
    pub manufacturer_type_descr: Vec<DtMlstring>,
    pub special_treatment_class: Vec<SpecialTreatmentClassElementType>,
    pub keyword: Vec<DtMlstring>,
    pub remarks: Vec<RemarksElementType>,
    pub product_status: Vec<ProductStatusElementType>,
}
#[derive(Debug)]
pub struct ProductFeaturesElementType {
    pub reference_feature_system_name: String,
    pub reference_feature_group_id: TypeClassificationGroupId,
    pub feature: Vec<FeatureElementType>,
}
#[derive(Debug)]
pub struct ProductOrderDetailsElementType {
    pub order_unit: DtPunit,
    pub content_unit: DtPunit,
    pub no_cu_per_ou: Option<f64>,
    pub price_quantity: Option<f64>,
    pub quantity_min: Option<f32>,
    pub quantity_interval: Option<f32>,
}
#[derive(Debug)]
pub struct ProductPriceDetailsElementType {
    pub datetime: Vec<ProductPriceDetailsDatetimeElementType>,
    pub daily_price: Option<String>,
    pub product_price: Vec<ProductPriceElementType>,
}
#[derive(Debug)]
pub struct UdxProduct {
    pub udx_edxf_manufacturer_acronym: Option<String>,
    pub udx_edxf_description_very_short: Vec<DtMlstring>,
    pub udx_edxf_brand_name: Option<String>,
    pub udx_edxf_tender_text: Vec<DtMlstring>,
    pub udx_edxf_valid_from: Option<String>,
    pub udx_edxf_expiration_date: Option<String>,
    pub udx_edxf_discount_group: Option<UdxEdxfDiscountGroupElementType>,
    pub udx_edxf_bonus_group_supplier: Option<String>,
    pub udx_edxf_pkwiu: Option<String>,
    pub udx_edxf_declaration: Vec<UdxEdxfDeclarationElementType>,
    pub udx_edxf_additional_factors: Option<UdxEdxfAdditionalFactorsElementType>,
    pub udx_edxf_product_to_stock: Option<String>,
    pub udx_edxf_product_series: Vec<DtMlstring>,
    pub udx_edxf_product_variation: Vec<DtMlstring>,
    pub udx_edxf_at_reverse_charge_info: Option<String>,
    pub udx_edxf_country_branch_numbers: Option<UdxEdxfCountryBranchNumbersElementType>,
    pub udx_edxf_country_branch_supplier_ids: Option<UdxEdxfCountryBranchSupplierIdsElementType>,
    pub udx_edxf_packing_units: Option<UdxEdxfPackingUnitsElementType>,
    pub udx_edxf_product_logistic_details: Option<UdxEdxfProductLogisticDetailsElementType>,
    pub udx_edxf_reach: Option<UdxEdxfReachElementType>,
    pub udx_edxf_surcharge_list: Option<UdxEdxfSurchargeListElementType>,
}
#[derive(Debug)]
pub struct ProductReferenceElementType {
    pub type_: ProductReferenceType,
    pub quantity: Option<i32>,
    pub prod_id_to: String,
    pub catalog_id: Option<String>,
    pub catalog_version: Option<String>,
}
#[derive(Debug)]
pub struct ProductLogisticDetailsElementType {
    pub customs_tariff_number: Vec<CustomsTariffNumberElementType>,
    pub statistics_factor: Option<f64>,
    pub country_of_origin: Vec<String>,
}
#[derive(Debug)]
pub enum TUpdateProductsMode {
    Delete,
    New,
    Update,
}
#[derive(Debug)]
pub enum TUpdatePricesMode {
    Update,
}
#[derive(Debug)]
pub enum DtLang {
    Aar,
    Abk,
    Ace,
    Ach,
    Ada,
    Afa,
    Afh,
    Afr,
    Aka,
    Akk,
    Alb,
    Ale,
    Alg,
    Amh,
    Ang,
    Apa,
    Ara,
    Arc,
    Arm,
    Arn,
    Arp,
    Art,
    Arw,
    Asm,
    Ath,
    Aus,
    Ava,
    Ave,
    Awa,
    Aym,
    Aze,
    Bad,
    Bai,
    Bak,
    Bal,
    Bam,
    Ban,
    Baq,
    Bas,
    Bat,
    Bej,
    Bel,
    Bem,
    Ben,
    Ber,
    Bho,
    Bih,
    Bik,
    Bin,
    Bis,
    Bla,
    Bnt,
    Bod,
    Bos,
    Bra,
    Bre,
    Btk,
    Bua,
    Bug,
    Bul,
    Bur,
    Cad,
    Cai,
    Car,
    Cat,
    Cau,
    Ceb,
    Cel,
    Ces,
    Cha,
    Chb,
    Che,
    Chg,
    Chi,
    Chk,
    Chm,
    Chn,
    Cho,
    Chp,
    Chr,
    Chu,
    Chv,
    Chy,
    Cmc,
    Cop,
    Cor,
    Cos,
    Cpe,
    Cpf,
    Cpp,
    Cre,
    Crp,
    Cus,
    Cym,
    Cze,
    Dak,
    Dan,
    Day,
    Del,
    Den,
    Deu,
    Dgr,
    Din,
    Div,
    Doi,
    Dra,
    Dua,
    Dum,
    Dut,
    Dyu,
    Dzo,
    Efi,
    Egy,
    Eka,
    Ell,
    Elx,
    Eng,
    Enm,
    Epo,
    Est,
    Eus,
    Ewe,
    Ewo,
    Fan,
    Fao,
    Fas,
    Fat,
    Fij,
    Fin,
    Fiu,
    Fon,
    Fra,
    Fre,
    Frm,
    Fro,
    Fry,
    Ful,
    Fur,
    Gaa,
    Gay,
    Gba,
    Gem,
    Geo,
    Ger,
    Gez,
    Gil,
    Gla,
    Gle,
    Glg,
    Glv,
    Gmh,
    Goh,
    Gon,
    Gor,
    Got,
    Grb,
    Grc,
    Gre,
    Grn,
    Guj,
    Gwi,
    Hai,
    Hau,
    Haw,
    Heb,
    Her,
    Hil,
    Him,
    Hin,
    Hit,
    Hmn,
    Hmo,
    Hrv,
    Hun,
    Hup,
    Hye,
    Iba,
    Ibo,
    Ice,
    Ijo,
    Iku,
    Ile,
    Ilo,
    Ina,
    Inc,
    Ind,
    Ine,
    Ipk,
    Ira,
    Iro,
    Isl,
    Ita,
    Jav,
    Jpn,
    Jpr,
    Jrb,
    Kaa,
    Kab,
    Kac,
    Kal,
    Kam,
    Kan,
    Kar,
    Kas,
    Kat,
    Kau,
    Kaw,
    Kaz,
    Kha,
    Khi,
    Khm,
    Kho,
    Kik,
    Kin,
    Kir,
    Kmb,
    Kok,
    Kom,
    Kon,
    Kor,
    Kos,
    Kpe,
    Kro,
    Kru,
    Kua,
    Kum,
    Kur,
    Kut,
    Lad,
    Lah,
    Lam,
    Lao,
    Lat,
    Lav,
    Lez,
    Lin,
    Lit,
    Lol,
    Loz,
    Ltz,
    Lua,
    Lub,
    Lug,
    Lui,
    Lun,
    Luo,
    Lus,
    Mac,
    Mad,
    Mag,
    Mah,
    Mai,
    Mak,
    Mal,
    Man,
    Mao,
    Map,
    Mar,
    Mas,
    May,
    Mdr,
    Men,
    Mga,
    Mic,
    Min,
    Mis,
    Mkd,
    Mkh,
    Mlg,
    Mlt,
    Mnc,
    Mni,
    Mno,
    Moh,
    Mol,
    Mon,
    Mos,
    Mri,
    Msa,
    Mul,
    Mun,
    Mus,
    Mwr,
    Mya,
    Myn,
    Nah,
    Nai,
    Nau,
    Nav,
    Nbl,
    Nde,
    Ndo,
    Nds,
    Nep,
    New,
    Nia,
    Nic,
    Niu,
    Nld,
    Nno,
    Nob,
    Non,
    Nor,
    Nso,
    Nub,
    Nya,
    Nym,
    Nyn,
    Nyo,
    Nzi,
    Oci,
    Oji,
    Ori,
    Orm,
    Osa,
    Oss,
    Ota,
    Oto,
    Paa,
    Pag,
    Pal,
    Pam,
    Pan,
    Pap,
    Pau,
    Peo,
    Per,
    Phi,
    Phn,
    Pli,
    Pol,
    Pon,
    Por,
    Pra,
    Pro,
    Pus,
    Qaa,
    Que,
    Raj,
    Rap,
    Rar,
    Roa,
    Roh,
    Rom,
    Ron,
    Rum,
    Run,
    Rus,
    Sad,
    Sag,
    Sah,
    Sai,
    Sal,
    Sam,
    San,
    Sas,
    Sat,
    Scc,
    Sco,
    Scr,
    Sel,
    Sem,
    Sga,
    Sgn,
    Shn,
    Sid,
    Sin,
    Sio,
    Sit,
    Sla,
    Slk,
    Slo,
    Slv,
    Sme,
    Smi,
    Smo,
    Sna,
    Snd,
    Snk,
    Sog,
    Som,
    Son,
    Sot,
    Spa,
    Sqi,
    Srd,
    Srp,
    Srr,
    Ssa,
    Ssw,
    Suk,
    Sun,
    Sus,
    Sux,
    Swa,
    Swe,
    Syr,
    Tah,
    Tai,
    Tam,
    Tat,
    Tel,
    Tem,
    Ter,
    Tet,
    Tgk,
    Tgl,
    Tha,
    Tib,
    Tig,
    Tir,
    Tiv,
    Tkl,
    Tli,
    Tmh,
    Tog,
    Ton,
    Tpi,
    Tsi,
    Tsn,
    Tso,
    Tuk,
    Tum,
    Tur,
    Tut,
    Tvl,
    Twi,
    Tyv,
    Uga,
    Uig,
    Ukr,
    Umb,
    Und,
    Urd,
    Uzb,
    Vai,
    Ven,
    Vie,
    Vol,
    Vot,
    Wak,
    Wal,
    War,
    Was,
    Wel,
    Wen,
    Wol,
    Xho,
    Yao,
    Yap,
    Yid,
    Yor,
    Ypk,
    Zap,
    Zen,
    Zha,
    Zho,
    Znd,
    Zul,
}
#[derive(Debug)]
pub enum CatalogType {
    GenerationDate,
}
#[derive(Debug)]
pub enum SupplierType {
    Supplier,
}
#[derive(Debug)]
pub struct MimeElementType {
    pub mime_type: String,
    pub mime_source: Vec<DtMlstring>,
    pub mime_descr: Vec<DtMlstring>,
    pub mime_alt: Vec<DtMlstring>,
    pub mime_purpose: MimePurposeElementType,
}
#[derive(Debug)]
pub struct InternationalPidElementType {
    pub type_: Option<String>,
    pub content: String,
}
#[derive(Debug)]
pub struct BuyerPidElementType {
    pub type_: Option<String>,
    pub content: String,
}
#[derive(Debug)]
pub struct SpecialTreatmentClassElementType {
    pub type_: String,
    pub content: String,
}
#[derive(Debug)]
pub struct RemarksElementType {
    pub lang: Option<DtLang>,
    pub type_: Option<String>,
    pub content: String,
}
#[derive(Debug)]
pub struct ProductStatusElementType {
    pub lang: Option<DtLang>,
    pub type_: ProductStatusType,
    pub content: String,
}
#[derive(Debug)]
pub struct TypeClassificationGroupId {
    pub type_: Option<TypeClassificationGroupIdType>,
    pub content: String,
}
#[derive(Debug)]
pub struct FeatureElementType {
    pub fname: Vec<DtMlstring>,
    pub fvalue: Vec<DtMlstring>,
    pub funit: Option<String>,
    pub fvalue_details: Vec<DtMlstring>,
}
#[derive(Debug)]
pub enum DtPunit {
    Be,
    Bg,
    Bo,
    Bx,
    C62,
    Ca,
    Cl,
    Cmt,
    Cq,
    Cs,
    Ct,
    Dr,
    Grm,
    Kg,
    Kgm,
    Ltr,
    Mgm,
    Mlt,
    Mmt,
    Mtr,
    Pa,
    Pf,
    Pk,
    Pl,
    Pr,
    Pu,
    Rg,
    Rl,
    Ro,
    Sa,
    Set,
    St,
    Tn,
    Tu,
    Z2,
    Z3,
}
#[derive(Debug)]
pub struct ProductPriceDetailsDatetimeElementType {
    pub type_: ProductPriceDetailsType,
    pub date: String,
    pub time: Option<String>,
    pub timezone: Option<String>,
}
#[derive(Debug)]
pub struct ProductPriceElementType {
    pub price_type: String,
    pub price_amount: f64,
    pub price_currency: Option<DtCurrencies>,
    pub tax: Option<f64>,
    pub price_factor: Option<f64>,
    pub lower_bound: Option<f64>,
    pub territory: Vec<String>,
}
#[derive(Debug)]
pub struct UdxEdxfDiscountGroupElementType {
    pub content: Vec<UdxEdxfDiscountGroupElementTypeContent>,
}
#[derive(Debug)]
pub enum UdxEdxfDiscountGroupElementTypeContent {
    UdxEdxfDiscountGroupManufacturer(String),
    UdxEdxfDiscountGroupSupplier(String),
}
#[derive(Debug)]
pub struct UdxEdxfDeclarationElementType {
    pub type_: String,
    pub date: Option<String>,
    pub content: String,
}
#[derive(Debug)]
pub struct UdxEdxfAdditionalFactorsElementType {
    pub udx_edxf_additional_price_factor: f64,
    pub udx_edxf_additional_factor_info: DtMlstring,
}
#[derive(Debug)]
pub struct UdxEdxfCountryBranchNumbersElementType {
    pub udx_edxf_country_branch_number:
        Vec<UdxEdxfCountryBranchNumbersUdxEdxfCountryBranchNumberElementType>,
}
#[derive(Debug)]
pub struct UdxEdxfCountryBranchSupplierIdsElementType {
    pub udx_edxf_country_branch_supplier_id:
        Vec<UdxEdxfCountryBranchSupplierIdsUdxEdxfCountryBranchSupplierIdElementType>,
}
#[derive(Debug)]
pub struct UdxEdxfPackingUnitsElementType {
    pub udx_edxf_packing_unit: Vec<UdxEdxfPackingUnitElementType>,
}
#[derive(Debug)]
pub struct UdxEdxfProductLogisticDetailsElementType {
    pub udx_edxf_netweight: Option<f64>,
    pub udx_edxf_region_of_origin: Option<String>,
}
#[derive(Debug)]
pub struct UdxEdxfReachElementType {
    pub udx_edxf_reach_listdate: Option<String>,
    pub udx_edxf_reach_info: String,
}
#[derive(Debug)]
pub struct UdxEdxfSurchargeListElementType {
    pub udx_edxf_surcharge: Vec<UdxEdxfSurchargeElementType>,
}
#[derive(Debug)]
pub enum ProductReferenceType {
    Accessories,
    BaseProduct,
    ConsistsOf,
    DiffOrderunit,
    Followup,
    Mandatory,
    Similar,
    Select,
    Sparepart,
    Others,
}
#[derive(Debug)]
pub struct CustomsTariffNumberElementType {
    pub customs_number: String,
}
#[derive(Debug)]
pub enum MimePurposeElementType {
    DataSheet,
    Detail,
    Icon,
    Logo,
    Normal,
    SafetyDataSheet,
    Thumbnail,
    Others,
}
#[derive(Debug)]
pub enum ProductStatusType {
    Bargain,
    CoreProduct,
    New,
    NewProduct,
    OldProduct,
    Refurbished,
    Used,
    Others,
}
#[derive(Debug)]
pub enum TypeClassificationGroupIdType {
    Flat,
    Hierarchy,
}
#[derive(Debug)]
pub enum ProductPriceDetailsType {
    ValidStartDate,
    ValidEndDate,
}
#[derive(Debug)]
pub struct UdxEdxfCountryBranchNumbersUdxEdxfCountryBranchNumberElementType {
    pub type_: String,
    pub country: String,
    pub content: f64,
}
#[derive(Debug)]
pub struct UdxEdxfCountryBranchSupplierIdsUdxEdxfCountryBranchSupplierIdElementType {
    pub type_: String,
    pub country: String,
    pub content: f64,
}
#[derive(Debug)]
pub struct UdxEdxfPackingUnitElementType {
    pub udx_edxf_quantity_min: f32,
    pub udx_edxf_quantity_max: Option<f32>,
    pub udx_edxf_packing_unit_code: DtPunit,
    pub udx_edxf_packing_unit_name: Vec<DtMlstring>,
    pub udx_edxf_package_break: Option<String>,
    pub udx_edxf_volume: Option<f64>,
    pub udx_edxf_weight: Option<f64>,
    pub udx_edxf_length: Option<f64>,
    pub udx_edxf_width: Option<f64>,
    pub udx_edxf_depth: Option<f64>,
    pub udx_edxf_diameter: Option<f64>,
    pub udx_edxf_gtin: Option<String>,
    pub udx_edxf_gs_1128: Option<String>,
}
#[derive(Debug)]
pub struct UdxEdxfSurchargeElementType {
    pub content: Vec<UdxEdxfSurchargeElementTypeContent>,
}
#[derive(Debug)]
pub enum UdxEdxfSurchargeElementTypeContent {
    UdxEdxfSurchargeType(String),
    UdxEdxfSurchargeManner(String),
    UdxEdxfSurchargePercentage(f64),
    UdxEdxfSurchargePriceAmount(f64),
    UdxEdxfSurchargeCalculation(f64),
    UdxEdxfMaterialBasis(f64),
    UdxEdxfMaterialBasisWeight(f64),
    UdxEdxfMaterialBasisSurchargeThreshold(f64),
    UdxEdxfMaterialBasisSurchargeShutter(i32),
    UdxEdxfMaterialBasisSurchargeCredit(i32),
    UdxEdxfMaterialBasisSurchargeTable(DtMlstring),
}
